import Head from "next/head";
import Service from "../components/Service";
import AboutUs from "../components/AboutUs";
import OurProjects from "../components/OurProjects";
import ExpertsTeam from "../components/ExpertsTeam";
import Achievement from "../components/Achievement";
import VideoFeedback from "../components/VideoFeedback";
import Summary from "../components/Summary";
import Contact from "../components/Contact";
import WorkingSteps from "../components/WorkingSteps";
import Banner from "../components/Banner";
import Header from "../components/Header";
import { useState } from "react";

// import styles from '../styles/Home.module.css';

export default function Home() {
  const [close, setclose] = useState(false);
   const [open, setOpen] = useState(false);

   const handleHambarger = () => {
      setclose(true);
      setOpen(false);
   }

  return (
    <div>
      <Head>
        <title>Sol Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main>
        <Header close={close} setclose={setclose} open={open} setOpen={setOpen}></Header>
        {/* Banner section */}
        <div onClick={handleHambarger}>
          <Banner />

          {/* Service section */}
          <Service></Service>

          {/* About Us section */}
          <AboutUs></AboutUs>

          {/* Our Projects section */}
          <OurProjects></OurProjects>

          {/* Working Steps */}
          <WorkingSteps></WorkingSteps>

          {/* Experts Team section */}
          <ExpertsTeam></ExpertsTeam>

          {/* Achievement section */}
          <Achievement></Achievement>

          {/* Video and Feedback section*/}
          <VideoFeedback></VideoFeedback>

          {/* Summary section */}
          <Summary></Summary>

          {/* Contact section */}
          <Contact></Contact>
        </div>
      </main>
    </div>
  );
}
